const assert = require('node:assert/strict');
const fs = require('node:fs');

const manager = fs.readFileSync('js/sort-state-manager.js', 'utf8');
const importer = fs.readFileSync('js/pages/sort-import.js', 'utf8');
const wall = fs.readFileSync('js/pages/sort-wall.js', 'utf8');
const masterPage = fs.readFileSync('sort-master.html', 'utf8');
const masterScript = fs.readFileSync('js/pages/sort-master.js', 'utf8');
const scanScript = fs.readFileSync('js/pages/sort-scan.js', 'utf8');
const styles = fs.readFileSync('css/style.css', 'utf8');

assert.match(manager, /collection\('users'\).*collection\('sortDestinationMaster'\)/);
assert.match(manager, /encodeURIComponent\(String\(code\)\.trim\(\)\)/);
assert.doesNotMatch(manager, /tx\.get\(this\.destinationMaster\(\)\)/);
assert.match(manager, /async saveDestinationMasterEntries\(importEntries\)/);
assert.match(manager, /MAX_DESTINATION_MASTER_IMPORT_ENTRIES = 100/);
assert.match(masterPage, /id="entryError"[^>]*role="alert"/);
assert.match(masterPage, /id="cancelEntry" type="button"/);
assert.match(masterScript, /entryMessage\('仕分け先コードが重複しています'\)/);
assert.match(masterScript, /deleteDestinationMasterEntry\(code\)/);
assert.match(manager, /async deleteDestinationMasterEntry\(code\)/);
assert.match(manager, /action: 'deleted', before, after: null/);
assert.match(manager, /collection\('sortDestinationConfig'\)\.doc\('current'\)/);
assert.match(manager, /async saveDestinationConfig\(maxSlotNo\)/);
assert.match(manager, /配置No\.\$\{String\(value\.slotNo\).*現在の物理配置数/);
assert.match(manager, /取込データに物理配置数/);
assert.match(manager, /configuredMax === 0.*batch\.set\(this\.destinationConfig\(\)/s);
assert.doesNotMatch(masterScript, /recentlyDeletedSlot/);
assert.match(masterScript, /Math\.max\(configuredMaxSlotNo, \.\.\.entries/);
assert.match(importer, /dcode: readRequiredColumn\('colDestCode'/);
assert.match(importer, /masterEntries\.filter\(\(v\) => v\.enabled\)/);
assert.match(importer, /destinationName: master\.destinationName/);
assert.ok(importer.indexOf('if (missing.size)') < importer.indexOf('replaceActiveBatch('), '未登録検証は稼働バッチ切替より先に行う');
assert.ok(importer.indexOf('if (disabled.size)') < importer.indexOf('replaceActiveBatch('), '無効検証は稼働バッチ切替より先に行う');
assert.doesNotMatch(importer, /closeActiveBatchForReplacement/);
assert.match(wall, /Array\.from\(\{ length: count \}/);
assert.match(wall, /vacant: true/);
assert.doesNotMatch(wall, /\.slice\(start - 1, start - 1 \+ count\)/);
assert.match(scanScript, /<table class="sort-scan-table"><colgroup>/);
assert.match(scanScript, /Object\.values\(item\.allocations \|\| \{\}\)\.sort/);
assert.match(scanScript, /displayOrder.*return leftOrder - rightOrder/s);
assert.match(styles, /\.sort-scan-table th:nth-child\(4\),\.sort-scan-table td:nth-child\(4\) \{ text-align:center; \}/);

console.log('sort destination master checks passed');
